name: "SerweronLib"
version: ${pluginVersion}
main: pl.serweron.serweronLib.SerweronLib
api-version: '${pluginAPI}'
authors: [MasnyPen]
website: serweron.pl

permissions:
  serweronlib.admin:
    default: op