name: Build & Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPO_USER: ${{ secrets.REPO_USER }}
      REPO_PASS: ${{ secrets.REPO_PASS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Publish to repo
        run: ./gradlew publish
